// src/theme/runtime/color.rs

use crate::theme::data::{
    UiAccentColorPaletteData, UiColorPalettesData, UiGrayAccentColorPaletteData,
};
use bevy::prelude::*;

#[derive(Debug, Clone)]
pub struct UiColorPalettes {
    pub white: UiColorPalette,
    pub black: UiColorPalette,
    pub gray: UiColorPalette,
    pub mauve: UiColorPalette,
    pub slate: UiColorPalette,
    pub sage: UiColorPalette,
    pub olive: UiColorPalette,
    pub sand: UiColorPalette,
    pub tomato: UiColorPalette,
    pub red: UiColorPalette,
    pub ruby: UiColorPalette,
    pub crimson: UiColorPalette,
    pub pink: UiColorPalette,
    pub plum: UiColorPalette,
    pub purple: UiColorPalette,
    pub violet: UiColorPalette,
    pub iris: UiColorPalette,
    pub indigo: UiColorPalette,
    pub blue: UiColorPalette,
    pub cyan: UiColorPalette,
    pub teal: UiColorPalette,
    pub jade: UiColorPalette,
    pub green: UiColorPalette,
    pub grass: UiColorPalette,
    pub bronze: UiColorPalette,
    pub gold: UiColorPalette,
    pub brown: UiColorPalette,
    pub orange: UiColorPalette,
    pub amber: UiColorPalette,
    pub yellow: UiColorPalette,
    pub lime: UiColorPalette,
    pub mint: UiColorPalette,
    pub sky: UiColorPalette,
}

#[derive(Debug, Clone)]
pub struct UiColorPalette {
    pub background_primary: Color,
    pub background_secondary: Color,
    pub interaction_primary: Color,
    pub interaction_secondary: Color,
    pub interaction_tertiary: Color,
    pub border_primary: Color,
    pub border_secondary: Color,
    pub border_tertiary: Color,
    pub solid_primary: Color,
    pub solid_secondary: Color,
    pub text_primary: Color,
    pub text_secondary: Color,
}

#[derive(Debug, Clone)]
pub struct UiAccentColorPalette {
    pub background_primary: Color,
    pub background_secondary: Color,
    pub interaction_primary: Color,
    pub interaction_secondary: Color,
    pub interaction_tertiary: Color,
    pub border_primary: Color,
    pub border_secondary: Color,
    pub border_tertiary: Color,
    pub solid_primary: Color,
    pub solid_secondary: Color,
    pub text_primary: Color,
    pub text_secondary: Color,
}

#[derive(Debug, Clone)]
pub struct UiGrayAccentColorPalette {
    pub background_primary: Color,
    pub background_secondary: Color,
    pub interaction_primary: Color,
    pub interaction_secondary: Color,
    pub interaction_tertiary: Color,
    pub border_primary: Color,
    pub border_secondary: Color,
    pub border_tertiary: Color,
    pub solid_primary: Color,
    pub solid_secondary: Color,
    pub text_primary: Color,
    pub text_secondary: Color,
}
pub fn build_accent_color(data: &UiAccentColorPaletteData) -> UiAccentColorPalette {
    let conv_color = |c: [f32; 4]| Color::srgba(c[0], c[1], c[2], c[3]);
    UiAccentColorPalette {
        background_primary: conv_color(data.background_primary),
        background_secondary: conv_color(data.background_secondary),
        interaction_primary: conv_color(data.interaction_primary),
        interaction_secondary: conv_color(data.interaction_secondary),
        interaction_tertiary: conv_color(data.interaction_tertiary),
        border_primary: conv_color(data.border_primary),
        border_secondary: conv_color(data.border_secondary),
        border_tertiary: conv_color(data.border_tertiary),
        solid_primary: conv_color(data.solid_primary),
        solid_secondary: conv_color(data.solid_secondary),
        text_primary: conv_color(data.text_primary),
        text_secondary: conv_color(data.text_secondary),
    }
}
pub fn build_gray_accent_color(data: &UiGrayAccentColorPaletteData) -> UiGrayAccentColorPalette {
    let conv_color = |c: [f32; 4]| Color::srgba(c[0], c[1], c[2], c[3]);
    UiGrayAccentColorPalette {
        background_primary: conv_color(data.background_primary),
        background_secondary: conv_color(data.background_secondary),
        interaction_primary: conv_color(data.interaction_primary),
        interaction_secondary: conv_color(data.interaction_secondary),
        interaction_tertiary: conv_color(data.interaction_tertiary),
        border_primary: conv_color(data.border_primary),
        border_secondary: conv_color(data.border_secondary),
        border_tertiary: conv_color(data.border_tertiary),
        solid_primary: conv_color(data.solid_primary),
        solid_secondary: conv_color(data.solid_secondary),
        text_primary: conv_color(data.text_primary),
        text_secondary: conv_color(data.text_secondary),
    }
}

pub fn build(data: &UiColorPalettesData) -> UiColorPalettes {
    let conv_color = |c: [f32; 4]| Color::srgba(c[0], c[1], c[2], c[3]);
    UiColorPalettes {
        white: UiColorPalette {
            background_primary: conv_color(data.white.background_primary),
            background_secondary: conv_color(data.white.background_secondary),
            interaction_primary: conv_color(data.white.interaction_primary),
            interaction_secondary: conv_color(data.white.interaction_secondary),
            interaction_tertiary: conv_color(data.white.interaction_tertiary),
            border_primary: conv_color(data.white.border_primary),
            border_secondary: conv_color(data.white.border_secondary),
            border_tertiary: conv_color(data.white.border_tertiary),
            solid_primary: conv_color(data.white.solid_primary),
            solid_secondary: conv_color(data.white.solid_secondary),
            text_primary: conv_color(data.white.text_primary),
            text_secondary: conv_color(data.white.text_secondary),
        },
        black: UiColorPalette {
            background_primary: conv_color(data.black.background_primary),
            background_secondary: conv_color(data.black.background_secondary),
            interaction_primary: conv_color(data.black.interaction_primary),
            interaction_secondary: conv_color(data.black.interaction_secondary),
            interaction_tertiary: conv_color(data.black.interaction_tertiary),
            border_primary: conv_color(data.black.border_primary),
            border_secondary: conv_color(data.black.border_secondary),
            border_tertiary: conv_color(data.black.border_tertiary),
            solid_primary: conv_color(data.black.solid_primary),
            solid_secondary: conv_color(data.black.solid_secondary),
            text_primary: conv_color(data.black.text_primary),
            text_secondary: conv_color(data.black.text_secondary),
        },
        gray: UiColorPalette {
            background_primary: conv_color(data.gray.background_primary),
            background_secondary: conv_color(data.gray.background_secondary),
            interaction_primary: conv_color(data.gray.interaction_primary),
            interaction_secondary: conv_color(data.gray.interaction_secondary),
            interaction_tertiary: conv_color(data.gray.interaction_tertiary),
            border_primary: conv_color(data.gray.border_primary),
            border_secondary: conv_color(data.gray.border_secondary),
            border_tertiary: conv_color(data.gray.border_tertiary),
            solid_primary: conv_color(data.gray.solid_primary),
            solid_secondary: conv_color(data.gray.solid_secondary),
            text_primary: conv_color(data.gray.text_primary),
            text_secondary: conv_color(data.gray.text_secondary),
        },
        mauve: UiColorPalette {
            background_primary: conv_color(data.mauve.background_primary),
            background_secondary: conv_color(data.mauve.background_secondary),
            interaction_primary: conv_color(data.mauve.interaction_primary),
            interaction_secondary: conv_color(data.mauve.interaction_secondary),
            interaction_tertiary: conv_color(data.mauve.interaction_tertiary),
            border_primary: conv_color(data.mauve.border_primary),
            border_secondary: conv_color(data.mauve.border_secondary),
            border_tertiary: conv_color(data.mauve.border_tertiary),
            solid_primary: conv_color(data.mauve.solid_primary),
            solid_secondary: conv_color(data.mauve.solid_secondary),
            text_primary: conv_color(data.mauve.text_primary),
            text_secondary: conv_color(data.mauve.text_secondary),
        },
        slate: UiColorPalette {
            background_primary: conv_color(data.slate.background_primary),
            background_secondary: conv_color(data.slate.background_secondary),
            interaction_primary: conv_color(data.slate.interaction_primary),
            interaction_secondary: conv_color(data.slate.interaction_secondary),
            interaction_tertiary: conv_color(data.slate.interaction_tertiary),
            border_primary: conv_color(data.slate.border_primary),
            border_secondary: conv_color(data.slate.border_secondary),
            border_tertiary: conv_color(data.slate.border_tertiary),
            solid_primary: conv_color(data.slate.solid_primary),
            solid_secondary: conv_color(data.slate.solid_secondary),
            text_primary: conv_color(data.slate.text_primary),
            text_secondary: conv_color(data.slate.text_secondary),
        },
        sage: UiColorPalette {
            background_primary: conv_color(data.sage.background_primary),
            background_secondary: conv_color(data.sage.background_secondary),
            interaction_primary: conv_color(data.sage.interaction_primary),
            interaction_secondary: conv_color(data.sage.interaction_secondary),
            interaction_tertiary: conv_color(data.sage.interaction_tertiary),
            border_primary: conv_color(data.sage.border_primary),
            border_secondary: conv_color(data.sage.border_secondary),
            border_tertiary: conv_color(data.sage.border_tertiary),
            solid_primary: conv_color(data.sage.solid_primary),
            solid_secondary: conv_color(data.sage.solid_secondary),
            text_primary: conv_color(data.sage.text_primary),
            text_secondary: conv_color(data.sage.text_secondary),
        },
        olive: UiColorPalette {
            background_primary: conv_color(data.olive.background_primary),
            background_secondary: conv_color(data.olive.background_secondary),
            interaction_primary: conv_color(data.olive.interaction_primary),
            interaction_secondary: conv_color(data.olive.interaction_secondary),
            interaction_tertiary: conv_color(data.olive.interaction_tertiary),
            border_primary: conv_color(data.olive.border_primary),
            border_secondary: conv_color(data.olive.border_secondary),
            border_tertiary: conv_color(data.olive.border_tertiary),
            solid_primary: conv_color(data.olive.solid_primary),
            solid_secondary: conv_color(data.olive.solid_secondary),
            text_primary: conv_color(data.olive.text_primary),
            text_secondary: conv_color(data.olive.text_secondary),
        },
        sand: UiColorPalette {
            background_primary: conv_color(data.sand.background_primary),
            background_secondary: conv_color(data.sand.background_secondary),
            interaction_primary: conv_color(data.sand.interaction_primary),
            interaction_secondary: conv_color(data.sand.interaction_secondary),
            interaction_tertiary: conv_color(data.sand.interaction_tertiary),
            border_primary: conv_color(data.sand.border_primary),
            border_secondary: conv_color(data.sand.border_secondary),
            border_tertiary: conv_color(data.sand.border_tertiary),
            solid_primary: conv_color(data.sand.solid_primary),
            solid_secondary: conv_color(data.sand.solid_secondary),
            text_primary: conv_color(data.sand.text_primary),
            text_secondary: conv_color(data.sand.text_secondary),
        },
        tomato: UiColorPalette {
            background_primary: conv_color(data.tomato.background_primary),
            background_secondary: conv_color(data.tomato.background_secondary),
            interaction_primary: conv_color(data.tomato.interaction_primary),
            interaction_secondary: conv_color(data.tomato.interaction_secondary),
            interaction_tertiary: conv_color(data.tomato.interaction_tertiary),
            border_primary: conv_color(data.tomato.border_primary),
            border_secondary: conv_color(data.tomato.border_secondary),
            border_tertiary: conv_color(data.tomato.border_tertiary),
            solid_primary: conv_color(data.tomato.solid_primary),
            solid_secondary: conv_color(data.tomato.solid_secondary),
            text_primary: conv_color(data.tomato.text_primary),
            text_secondary: conv_color(data.tomato.text_secondary),
        },
        red: UiColorPalette {
            background_primary: conv_color(data.red.background_primary),
            background_secondary: conv_color(data.red.background_secondary),
            interaction_primary: conv_color(data.red.interaction_primary),
            interaction_secondary: conv_color(data.red.interaction_secondary),
            interaction_tertiary: conv_color(data.red.interaction_tertiary),
            border_primary: conv_color(data.red.border_primary),
            border_secondary: conv_color(data.red.border_secondary),
            border_tertiary: conv_color(data.red.border_tertiary),
            solid_primary: conv_color(data.red.solid_primary),
            solid_secondary: conv_color(data.red.solid_secondary),
            text_primary: conv_color(data.red.text_primary),
            text_secondary: conv_color(data.red.text_secondary),
        },
        ruby: UiColorPalette {
            background_primary: conv_color(data.ruby.background_primary),
            background_secondary: conv_color(data.ruby.background_secondary),
            interaction_primary: conv_color(data.ruby.interaction_primary),
            interaction_secondary: conv_color(data.ruby.interaction_secondary),
            interaction_tertiary: conv_color(data.ruby.interaction_tertiary),
            border_primary: conv_color(data.ruby.border_primary),
            border_secondary: conv_color(data.ruby.border_secondary),
            border_tertiary: conv_color(data.ruby.border_tertiary),
            solid_primary: conv_color(data.ruby.solid_primary),
            solid_secondary: conv_color(data.ruby.solid_secondary),
            text_primary: conv_color(data.ruby.text_primary),
            text_secondary: conv_color(data.ruby.text_secondary),
        },
        crimson: UiColorPalette {
            background_primary: conv_color(data.crimson.background_primary),
            background_secondary: conv_color(data.crimson.background_secondary),
            interaction_primary: conv_color(data.crimson.interaction_primary),
            interaction_secondary: conv_color(data.crimson.interaction_secondary),
            interaction_tertiary: conv_color(data.crimson.interaction_tertiary),
            border_primary: conv_color(data.crimson.border_primary),
            border_secondary: conv_color(data.crimson.border_secondary),
            border_tertiary: conv_color(data.crimson.border_tertiary),
            solid_primary: conv_color(data.crimson.solid_primary),
            solid_secondary: conv_color(data.crimson.solid_secondary),
            text_primary: conv_color(data.crimson.text_primary),
            text_secondary: conv_color(data.crimson.text_secondary),
        },
        pink: UiColorPalette {
            background_primary: conv_color(data.pink.background_primary),
            background_secondary: conv_color(data.pink.background_secondary),
            interaction_primary: conv_color(data.pink.interaction_primary),
            interaction_secondary: conv_color(data.pink.interaction_secondary),
            interaction_tertiary: conv_color(data.pink.interaction_tertiary),
            border_primary: conv_color(data.pink.border_primary),
            border_secondary: conv_color(data.pink.border_secondary),
            border_tertiary: conv_color(data.pink.border_tertiary),
            solid_primary: conv_color(data.pink.solid_primary),
            solid_secondary: conv_color(data.pink.solid_secondary),
            text_primary: conv_color(data.pink.text_primary),
            text_secondary: conv_color(data.pink.text_secondary),
        },
        plum: UiColorPalette {
            background_primary: conv_color(data.plum.background_primary),
            background_secondary: conv_color(data.plum.background_secondary),
            interaction_primary: conv_color(data.plum.interaction_primary),
            interaction_secondary: conv_color(data.plum.interaction_secondary),
            interaction_tertiary: conv_color(data.plum.interaction_tertiary),
            border_primary: conv_color(data.plum.border_primary),
            border_secondary: conv_color(data.plum.border_secondary),
            border_tertiary: conv_color(data.plum.border_tertiary),
            solid_primary: conv_color(data.plum.solid_primary),
            solid_secondary: conv_color(data.plum.solid_secondary),
            text_primary: conv_color(data.plum.text_primary),
            text_secondary: conv_color(data.plum.text_secondary),
        },
        purple: UiColorPalette {
            background_primary: conv_color(data.purple.background_primary),
            background_secondary: conv_color(data.purple.background_secondary),
            interaction_primary: conv_color(data.purple.interaction_primary),
            interaction_secondary: conv_color(data.purple.interaction_secondary),
            interaction_tertiary: conv_color(data.purple.interaction_tertiary),
            border_primary: conv_color(data.purple.border_primary),
            border_secondary: conv_color(data.purple.border_secondary),
            border_tertiary: conv_color(data.purple.border_tertiary),
            solid_primary: conv_color(data.purple.solid_primary),
            solid_secondary: conv_color(data.purple.solid_secondary),
            text_primary: conv_color(data.purple.text_primary),
            text_secondary: conv_color(data.purple.text_secondary),
        },
        violet: UiColorPalette {
            background_primary: conv_color(data.violet.background_primary),
            background_secondary: conv_color(data.violet.background_secondary),
            interaction_primary: conv_color(data.violet.interaction_primary),
            interaction_secondary: conv_color(data.violet.interaction_secondary),
            interaction_tertiary: conv_color(data.violet.interaction_tertiary),
            border_primary: conv_color(data.violet.border_primary),
            border_secondary: conv_color(data.violet.border_secondary),
            border_tertiary: conv_color(data.violet.border_tertiary),
            solid_primary: conv_color(data.violet.solid_primary),
            solid_secondary: conv_color(data.violet.solid_secondary),
            text_primary: conv_color(data.violet.text_primary),
            text_secondary: conv_color(data.violet.text_secondary),
        },
        iris: UiColorPalette {
            background_primary: conv_color(data.iris.background_primary),
            background_secondary: conv_color(data.iris.background_secondary),
            interaction_primary: conv_color(data.iris.interaction_primary),
            interaction_secondary: conv_color(data.iris.interaction_secondary),
            interaction_tertiary: conv_color(data.iris.interaction_tertiary),
            border_primary: conv_color(data.iris.border_primary),
            border_secondary: conv_color(data.iris.border_secondary),
            border_tertiary: conv_color(data.iris.border_tertiary),
            solid_primary: conv_color(data.iris.solid_primary),
            solid_secondary: conv_color(data.iris.solid_secondary),
            text_primary: conv_color(data.iris.text_primary),
            text_secondary: conv_color(data.iris.text_secondary),
        },
        indigo: UiColorPalette {
            background_primary: conv_color(data.indigo.background_primary),
            background_secondary: conv_color(data.indigo.background_secondary),
            interaction_primary: conv_color(data.indigo.interaction_primary),
            interaction_secondary: conv_color(data.indigo.interaction_secondary),
            interaction_tertiary: conv_color(data.indigo.interaction_tertiary),
            border_primary: conv_color(data.indigo.border_primary),
            border_secondary: conv_color(data.indigo.border_secondary),
            border_tertiary: conv_color(data.indigo.border_tertiary),
            solid_primary: conv_color(data.indigo.solid_primary),
            solid_secondary: conv_color(data.indigo.solid_secondary),
            text_primary: conv_color(data.indigo.text_primary),
            text_secondary: conv_color(data.indigo.text_secondary),
        },
        blue: UiColorPalette {
            background_primary: conv_color(data.blue.background_primary),
            background_secondary: conv_color(data.blue.background_secondary),
            interaction_primary: conv_color(data.blue.interaction_primary),
            interaction_secondary: conv_color(data.blue.interaction_secondary),
            interaction_tertiary: conv_color(data.blue.interaction_tertiary),
            border_primary: conv_color(data.blue.border_primary),
            border_secondary: conv_color(data.blue.border_secondary),
            border_tertiary: conv_color(data.blue.border_tertiary),
            solid_primary: conv_color(data.blue.solid_primary),
            solid_secondary: conv_color(data.blue.solid_secondary),
            text_primary: conv_color(data.blue.text_primary),
            text_secondary: conv_color(data.blue.text_secondary),
        },
        cyan: UiColorPalette {
            background_primary: conv_color(data.cyan.background_primary),
            background_secondary: conv_color(data.cyan.background_secondary),
            interaction_primary: conv_color(data.cyan.interaction_primary),
            interaction_secondary: conv_color(data.cyan.interaction_secondary),
            interaction_tertiary: conv_color(data.cyan.interaction_tertiary),
            border_primary: conv_color(data.cyan.border_primary),
            border_secondary: conv_color(data.cyan.border_secondary),
            border_tertiary: conv_color(data.cyan.border_tertiary),
            solid_primary: conv_color(data.cyan.solid_primary),
            solid_secondary: conv_color(data.cyan.solid_secondary),
            text_primary: conv_color(data.cyan.text_primary),
            text_secondary: conv_color(data.cyan.text_secondary),
        },
        teal: UiColorPalette {
            background_primary: conv_color(data.teal.background_primary),
            background_secondary: conv_color(data.teal.background_secondary),
            interaction_primary: conv_color(data.teal.interaction_primary),
            interaction_secondary: conv_color(data.teal.interaction_secondary),
            interaction_tertiary: conv_color(data.teal.interaction_tertiary),
            border_primary: conv_color(data.teal.border_primary),
            border_secondary: conv_color(data.teal.border_secondary),
            border_tertiary: conv_color(data.teal.border_tertiary),
            solid_primary: conv_color(data.teal.solid_primary),
            solid_secondary: conv_color(data.teal.solid_secondary),
            text_primary: conv_color(data.teal.text_primary),
            text_secondary: conv_color(data.teal.text_secondary),
        },
        jade: UiColorPalette {
            background_primary: conv_color(data.jade.background_primary),
            background_secondary: conv_color(data.jade.background_secondary),
            interaction_primary: conv_color(data.jade.interaction_primary),
            interaction_secondary: conv_color(data.jade.interaction_secondary),
            interaction_tertiary: conv_color(data.jade.interaction_tertiary),
            border_primary: conv_color(data.jade.border_primary),
            border_secondary: conv_color(data.jade.border_secondary),
            border_tertiary: conv_color(data.jade.border_tertiary),
            solid_primary: conv_color(data.jade.solid_primary),
            solid_secondary: conv_color(data.jade.solid_secondary),
            text_primary: conv_color(data.jade.text_primary),
            text_secondary: conv_color(data.jade.text_secondary),
        },
        green: UiColorPalette {
            background_primary: conv_color(data.green.background_primary),
            background_secondary: conv_color(data.green.background_secondary),
            interaction_primary: conv_color(data.green.interaction_primary),
            interaction_secondary: conv_color(data.green.interaction_secondary),
            interaction_tertiary: conv_color(data.green.interaction_tertiary),
            border_primary: conv_color(data.green.border_primary),
            border_secondary: conv_color(data.green.border_secondary),
            border_tertiary: conv_color(data.green.border_tertiary),
            solid_primary: conv_color(data.green.solid_primary),
            solid_secondary: conv_color(data.green.solid_secondary),
            text_primary: conv_color(data.green.text_primary),
            text_secondary: conv_color(data.green.text_secondary),
        },
        grass: UiColorPalette {
            background_primary: conv_color(data.grass.background_primary),
            background_secondary: conv_color(data.grass.background_secondary),
            interaction_primary: conv_color(data.grass.interaction_primary),
            interaction_secondary: conv_color(data.grass.interaction_secondary),
            interaction_tertiary: conv_color(data.grass.interaction_tertiary),
            border_primary: conv_color(data.grass.border_primary),
            border_secondary: conv_color(data.grass.border_secondary),
            border_tertiary: conv_color(data.grass.border_tertiary),
            solid_primary: conv_color(data.grass.solid_primary),
            solid_secondary: conv_color(data.grass.solid_secondary),
            text_primary: conv_color(data.grass.text_primary),
            text_secondary: conv_color(data.grass.text_secondary),
        },
        bronze: UiColorPalette {
            background_primary: conv_color(data.bronze.background_primary),
            background_secondary: conv_color(data.bronze.background_secondary),
            interaction_primary: conv_color(data.bronze.interaction_primary),
            interaction_secondary: conv_color(data.bronze.interaction_secondary),
            interaction_tertiary: conv_color(data.bronze.interaction_tertiary),
            border_primary: conv_color(data.bronze.border_primary),
            border_secondary: conv_color(data.bronze.border_secondary),
            border_tertiary: conv_color(data.bronze.border_tertiary),
            solid_primary: conv_color(data.bronze.solid_primary),
            solid_secondary: conv_color(data.bronze.solid_secondary),
            text_primary: conv_color(data.bronze.text_primary),
            text_secondary: conv_color(data.bronze.text_secondary),
        },
        gold: UiColorPalette {
            background_primary: conv_color(data.gold.background_primary),
            background_secondary: conv_color(data.gold.background_secondary),
            interaction_primary: conv_color(data.gold.interaction_primary),
            interaction_secondary: conv_color(data.gold.interaction_secondary),
            interaction_tertiary: conv_color(data.gold.interaction_tertiary),
            border_primary: conv_color(data.gold.border_primary),
            border_secondary: conv_color(data.gold.border_secondary),
            border_tertiary: conv_color(data.gold.border_tertiary),
            solid_primary: conv_color(data.gold.solid_primary),
            solid_secondary: conv_color(data.gold.solid_secondary),
            text_primary: conv_color(data.gold.text_primary),
            text_secondary: conv_color(data.gold.text_secondary),
        },
        brown: UiColorPalette {
            background_primary: conv_color(data.brown.background_primary),
            background_secondary: conv_color(data.brown.background_secondary),
            interaction_primary: conv_color(data.brown.interaction_primary),
            interaction_secondary: conv_color(data.brown.interaction_secondary),
            interaction_tertiary: conv_color(data.brown.interaction_tertiary),
            border_primary: conv_color(data.brown.border_primary),
            border_secondary: conv_color(data.brown.border_secondary),
            border_tertiary: conv_color(data.brown.border_tertiary),
            solid_primary: conv_color(data.brown.solid_primary),
            solid_secondary: conv_color(data.brown.solid_secondary),
            text_primary: conv_color(data.brown.text_primary),
            text_secondary: conv_color(data.brown.text_secondary),
        },
        orange: UiColorPalette {
            background_primary: conv_color(data.orange.background_primary),
            background_secondary: conv_color(data.orange.background_secondary),
            interaction_primary: conv_color(data.orange.interaction_primary),
            interaction_secondary: conv_color(data.orange.interaction_secondary),
            interaction_tertiary: conv_color(data.orange.interaction_tertiary),
            border_primary: conv_color(data.orange.border_primary),
            border_secondary: conv_color(data.orange.border_secondary),
            border_tertiary: conv_color(data.orange.border_tertiary),
            solid_primary: conv_color(data.orange.solid_primary),
            solid_secondary: conv_color(data.orange.solid_secondary),
            text_primary: conv_color(data.orange.text_primary),
            text_secondary: conv_color(data.orange.text_secondary),
        },
        amber: UiColorPalette {
            background_primary: conv_color(data.amber.background_primary),
            background_secondary: conv_color(data.amber.background_secondary),
            interaction_primary: conv_color(data.amber.interaction_primary),
            interaction_secondary: conv_color(data.amber.interaction_secondary),
            interaction_tertiary: conv_color(data.amber.interaction_tertiary),
            border_primary: conv_color(data.amber.border_primary),
            border_secondary: conv_color(data.amber.border_secondary),
            border_tertiary: conv_color(data.amber.border_tertiary),
            solid_primary: conv_color(data.amber.solid_primary),
            solid_secondary: conv_color(data.amber.solid_secondary),
            text_primary: conv_color(data.amber.text_primary),
            text_secondary: conv_color(data.amber.text_secondary),
        },
        yellow: UiColorPalette {
            background_primary: conv_color(data.yellow.background_primary),
            background_secondary: conv_color(data.yellow.background_secondary),
            interaction_primary: conv_color(data.yellow.interaction_primary),
            interaction_secondary: conv_color(data.yellow.interaction_secondary),
            interaction_tertiary: conv_color(data.yellow.interaction_tertiary),
            border_primary: conv_color(data.yellow.border_primary),
            border_secondary: conv_color(data.yellow.border_secondary),
            border_tertiary: conv_color(data.yellow.border_tertiary),
            solid_primary: conv_color(data.yellow.solid_primary),
            solid_secondary: conv_color(data.yellow.solid_secondary),
            text_primary: conv_color(data.yellow.text_primary),
            text_secondary: conv_color(data.yellow.text_secondary),
        },
        lime: UiColorPalette {
            background_primary: conv_color(data.lime.background_primary),
            background_secondary: conv_color(data.lime.background_secondary),
            interaction_primary: conv_color(data.lime.interaction_primary),
            interaction_secondary: conv_color(data.lime.interaction_secondary),
            interaction_tertiary: conv_color(data.lime.interaction_tertiary),
            border_primary: conv_color(data.lime.border_primary),
            border_secondary: conv_color(data.lime.border_secondary),
            border_tertiary: conv_color(data.lime.border_tertiary),
            solid_primary: conv_color(data.lime.solid_primary),
            solid_secondary: conv_color(data.lime.solid_secondary),
            text_primary: conv_color(data.lime.text_primary),
            text_secondary: conv_color(data.lime.text_secondary),
        },
        mint: UiColorPalette {
            background_primary: conv_color(data.mint.background_primary),
            background_secondary: conv_color(data.mint.background_secondary),
            interaction_primary: conv_color(data.mint.interaction_primary),
            interaction_secondary: conv_color(data.mint.interaction_secondary),
            interaction_tertiary: conv_color(data.mint.interaction_tertiary),
            border_primary: conv_color(data.mint.border_primary),
            border_secondary: conv_color(data.mint.border_secondary),
            border_tertiary: conv_color(data.mint.border_tertiary),
            solid_primary: conv_color(data.mint.solid_primary),
            solid_secondary: conv_color(data.mint.solid_secondary),
            text_primary: conv_color(data.mint.text_primary),
            text_secondary: conv_color(data.mint.text_secondary),
        },
        sky: UiColorPalette {
            background_primary: conv_color(data.sky.background_primary),
            background_secondary: conv_color(data.sky.background_secondary),
            interaction_primary: conv_color(data.sky.interaction_primary),
            interaction_secondary: conv_color(data.sky.interaction_secondary),
            interaction_tertiary: conv_color(data.sky.interaction_tertiary),
            border_primary: conv_color(data.sky.border_primary),
            border_secondary: conv_color(data.sky.border_secondary),
            border_tertiary: conv_color(data.sky.border_tertiary),
            solid_primary: conv_color(data.sky.solid_primary),
            solid_secondary: conv_color(data.sky.solid_secondary),
            text_primary: conv_color(data.sky.text_primary),
            text_secondary: conv_color(data.sky.text_secondary),
        },
    }
}
