// crates/forge_ui/src/theme/runtime.rs
use bevy::{color::Srgba, prelude::*, reflect::TypePath}; // <<< TypePath hinzufügen

const REM: f32 = 16.0;
const SPACING: f32 = 4.0;

#[derive(Debug, Clone, Asset, TypePath, Resource)]
pub struct UiTheme {
    pub ui_scaling: f32,
    pub font: UiTypography,
    pub layout: UiLayout,
    pub color: UiColors,
}

#[derive(Debug, Clone)]
pub struct UiTypography {
    pub font_size: UiFontSize,
    pub font_family: UiFontFamilies,
}

#[derive(Debug, Clone)]
pub struct UiLayout {
    pub spacing: f32,
    pub padding: UiSpacing,
    pub margin: UiSpacing,
    pub gap: UiSpacing,
    pub radius: UiRadius,
    pub border: UiSpacing,
}

#[derive(Debug, Clone)]
pub struct UiColors {
    pub white: UiColor,
    pub black: UiColor,
    pub gray: UiColor,
    pub mauve: UiColor,
    pub slate: UiColor,
    pub sage: UiColor,
    pub olive: UiColor,
    pub sand: UiColor,
    pub tomato: UiColor,
    pub red: UiColor,
    pub ruby: UiColor,
    pub crimson: UiColor,
    pub pink: UiColor,
    pub plum: UiColor,
    pub purple: UiColor,
    pub violet: UiColor,
    pub iris: UiColor,
    pub indigo: UiColor,
    pub blue: UiColor,
    pub cyan: UiColor,
    pub teal: UiColor,
    pub jade: UiColor,
    pub green: UiColor,
    pub grass: UiColor,
    pub bronze: UiColor,
    pub gold: UiColor,
    pub brown: UiColor,
    pub orange: UiColor,
    pub amber: UiColor,
    pub yellow: UiColor,
    pub lime: UiColor,
    pub mint: UiColor,
    pub sky: UiColor,
}

#[derive(Debug, Clone)]
pub struct UiFontSize {
    pub xs: f32,
    pub sm: f32,
    pub base: f32,
    pub lg: f32,
    pub xl: f32,
    pub x2l: f32,
    pub x3l: f32,
    pub x4l: f32,
    pub x5l: f32,
    pub x6l: f32,
    pub x7l: f32,
    pub x8l: f32,
    pub x9l: f32,
}

#[derive(Debug, Clone)]
pub struct UiFontFamilies {
    pub default: Handle<Font>,
    pub sans: FontVariants,
    pub serif: FontVariants,
    pub mono: FontVariants,
}

#[derive(Debug, Clone)]
pub struct FontVariants {
    pub light: Handle<Font>,
    pub light_italic: Handle<Font>,
    pub regular: Handle<Font>,
    pub regular_italic: Handle<Font>,
    pub medium: Handle<Font>,
    pub medium_italic: Handle<Font>,
    pub bold: Handle<Font>,
    pub bold_italic: Handle<Font>,
}

#[derive(Debug, Clone)]
pub struct UiSpacing {
    pub xs: f32,
    pub sm: f32,
    pub base: f32,
    pub lg: f32,
    pub xl: f32,
    pub x2l: f32,
    pub x3l: f32,
    pub x4l: f32,
    pub x5l: f32,
}
#[derive(Debug, Clone)]
pub struct UiRadius {
    pub xs: f32,
    pub sm: f32,
    pub base: f32,
    pub lg: f32,
    pub xl: f32,
    pub x2l: f32,
    pub x3l: f32,
    pub x4l: f32,
    pub full: f32,
}

#[derive(Debug, Clone)]
pub struct UiColor {
    pub background_primary: Color,
    pub background_secondary: Color,

    pub interaction_primary: Color,
    pub interaction_secondary: Color,
    pub interaction_tertiary: Color,

    pub border_primary: Color,
    pub border_secondary: Color,
    pub border_tertiary: Color,

    pub solid_primary: Color,
    pub solid_secondary: Color,

    pub text_primary: Color,
    pub text_secondary: Color,
}

// Default implementation remains mostly the same, but needs to provide default Handles
// Note: Providing valid default Handles here is tricky. This default might panic
// if used before assets are loaded properly. It's better practice to load from
// file and ensure the resource exists before using it.
impl Default for UiTheme {
    fn default() -> Self {
        // Placeholder handles - these WILL NOT WORK unless assets with these exact IDs exist!
        let placeholder_font = Handle::default(); // Use default handle as placeholder

        Self {
            ui_scaling: 1.0,
            color: UiColors {
                white: UiColor {
                    background_primary: Color::WHITE.with_alpha(0.05),
                    background_secondary: Color::WHITE.with_alpha(0.1),
                    interaction_primary: Color::WHITE.with_alpha(0.15),
                    interaction_secondary: Color::WHITE.with_alpha(0.2),
                    interaction_tertiary: Color::WHITE.with_alpha(0.3),
                    border_primary: Color::WHITE.with_alpha(0.4),
                    border_secondary: Color::WHITE.with_alpha(0.5),
                    border_tertiary: Color::WHITE.with_alpha(0.6),
                    solid_primary: Color::WHITE.with_alpha(0.7),
                    solid_secondary: Color::WHITE.with_alpha(0.8),
                    text_primary: Color::WHITE.with_alpha(0.9),
                    text_secondary: Color::WHITE.with_alpha(0.95),
                },
                black: UiColor {
                    background_primary: Color::BLACK.with_alpha(0.05),
                    background_secondary: Color::BLACK.with_alpha(0.1),
                    interaction_primary: Color::BLACK.with_alpha(0.15),
                    interaction_secondary: Color::BLACK.with_alpha(0.2),
                    interaction_tertiary: Color::BLACK.with_alpha(0.3),
                    border_primary: Color::BLACK.with_alpha(0.4),
                    border_secondary: Color::BLACK.with_alpha(0.5),
                    border_tertiary: Color::BLACK.with_alpha(0.6),
                    solid_primary: Color::BLACK.with_alpha(0.7),
                    solid_secondary: Color::BLACK.with_alpha(0.8),
                    text_primary: Color::BLACK.with_alpha(0.9),
                    text_secondary: Color::BLACK.with_alpha(0.95),
                },
                gray: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                mauve: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                slate: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                sage: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                olive: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                sand: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                tomato: UiColor {
                    background_primary: Srgba::hex("181111").unwrap().into(),
                    background_secondary: Srgba::hex("1F1513").unwrap().into(),
                    interaction_primary: Srgba::hex("391714").unwrap().into(),
                    interaction_secondary: Srgba::hex("4E1511").unwrap().into(),
                    interaction_tertiary: Srgba::hex("5E1C16").unwrap().into(),
                    border_primary: Srgba::hex("6E2920").unwrap().into(),
                    border_secondary: Srgba::hex("853A2D").unwrap().into(),
                    border_tertiary: Srgba::hex("AC4D39").unwrap().into(),
                    solid_primary: Srgba::hex("E54D2E").unwrap().into(),
                    solid_secondary: Srgba::hex("EC6142").unwrap().into(),
                    text_primary: Srgba::hex("FF977D").unwrap().into(),
                    text_secondary: Srgba::hex("FBD3CB").unwrap().into(),
                },
                red: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                ruby: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                crimson: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                pink: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                plum: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                purple: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                violet: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                iris: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                indigo: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                blue: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                cyan: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                teal: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                jade: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                green: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                grass: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                bronze: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                gold: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                brown: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                orange: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                amber: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                yellow: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                lime: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                mint: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
                sky: UiColor {
                    background_primary: Srgba::hex("111111").unwrap().into(),
                    background_secondary: Srgba::hex("191919").unwrap().into(),
                    interaction_primary: Srgba::hex("222222").unwrap().into(),
                    interaction_secondary: Srgba::hex("2A2A2A").unwrap().into(),
                    interaction_tertiary: Srgba::hex("313131").unwrap().into(),
                    border_primary: Srgba::hex("3A3A3A").unwrap().into(),
                    border_secondary: Srgba::hex("484848").unwrap().into(),
                    border_tertiary: Srgba::hex("606060").unwrap().into(),
                    solid_primary: Srgba::hex("6E6E6E").unwrap().into(),
                    solid_secondary: Srgba::hex("7B7B7B").unwrap().into(),
                    text_primary: Srgba::hex("B4B4B4").unwrap().into(),
                    text_secondary: Srgba::hex("EEEEEE").unwrap().into(),
                },
            },
            layout: UiLayout {
                spacing: SPACING,
                padding: UiSpacing {
                    xs: 1.0 * SPACING,
                    sm: 2.0 * SPACING,
                    base: 3.0 * SPACING,
                    lg: 4.0 * SPACING,
                    xl: 5.0 * SPACING,
                    x2l: 6.0 * SPACING,
                    x3l: 7.0 * SPACING,
                    x4l: 8.0 * SPACING,
                    x5l: 9.0 * SPACING,
                },
                margin: UiSpacing {
                    xs: 1.0 * SPACING,
                    sm: 2.0 * SPACING,
                    base: 3.0 * SPACING,
                    lg: 4.0 * SPACING,
                    xl: 5.0 * SPACING,
                    x2l: 6.0 * SPACING,
                    x3l: 7.0 * SPACING,
                    x4l: 8.0 * SPACING,
                    x5l: 9.0 * SPACING,
                },
                gap: UiSpacing {
                    xs: 1.0 * SPACING,
                    sm: 2.0 * SPACING,
                    base: 3.0 * SPACING,
                    lg: 4.0 * SPACING,
                    xl: 5.0 * SPACING,
                    x2l: 6.0 * SPACING,
                    x3l: 7.0 * SPACING,
                    x4l: 8.0 * SPACING,
                    x5l: 9.0 * SPACING,
                },
                radius: UiRadius {
                    xs: 0.125 * REM,
                    sm: 0.25 * REM,
                    base: 0.375 * REM,
                    lg: 0.5 * REM,
                    xl: 0.75 * REM,
                    x2l: 1.0 * REM,
                    x3l: 1.5 * REM,
                    x4l: 2.0 * REM,
                    full: f32::MAX,
                },
                border: UiSpacing {
                    xs: 1.0,
                    sm: 2.0,
                    base: 3.0,
                    lg: 5.0,
                    xl: 7.0,
                    x2l: 9.0,
                    x3l: 12.0,
                    x4l: 15.0,
                    x5l: 19.0,
                },
            },
            font: UiTypography {
                font_size: UiFontSize {
                    xs: 0.75 * REM,
                    sm: 0.875 * REM,
                    base: 1.0 * REM,
                    lg: 1.125 * REM,
                    xl: 1.25 * REM,
                    x2l: 1.5 * REM,
                    x3l: 1.875 * REM,
                    x4l: 2.25 * REM,
                    x5l: 3.0 * REM,
                    x6l: 3.75 * REM,
                    x7l: 4.5 * REM,
                    x8l: 6.0 * REM,
                    x9l: 8.0 * REM,
                },
                font_family: UiFontFamilies {
                    default: placeholder_font.clone(),
                    sans: FontVariants {
                        light: placeholder_font.clone(),
                        light_italic: placeholder_font.clone(),
                        regular: placeholder_font.clone(),
                        regular_italic: placeholder_font.clone(),
                        medium: placeholder_font.clone(),
                        medium_italic: placeholder_font.clone(),
                        bold: placeholder_font.clone(),
                        bold_italic: placeholder_font.clone(),
                    },
                    serif: FontVariants {
                        light: placeholder_font.clone(),
                        light_italic: placeholder_font.clone(),
                        regular: placeholder_font.clone(),
                        regular_italic: placeholder_font.clone(),
                        medium: placeholder_font.clone(),
                        medium_italic: placeholder_font.clone(),
                        bold: placeholder_font.clone(),
                        bold_italic: placeholder_font.clone(),
                    },
                    mono: FontVariants {
                        light: placeholder_font.clone(),
                        light_italic: placeholder_font.clone(),
                        regular: placeholder_font.clone(),
                        regular_italic: placeholder_font.clone(),
                        medium: placeholder_font.clone(),
                        medium_italic: placeholder_font.clone(),
                        bold: placeholder_font.clone(),
                        bold_italic: placeholder_font.clone(),
                    },
                },
            },
        }
    }
}
