// crates/forge_ui/src/theme/runtime.rs
use crate::plugin::UiConfig;
use crate::theme::data::UiThemeData;
use bevy::{prelude::*, reflect::TypePath};

#[derive(Debug, Clone, Asset, TypePath, Resource)]
pub struct UiTheme {
    pub ui_scaling: f32,
    pub rem: f32,
    pub font: UiTypography,
    pub layout: UiLayout,
    pub color: UiColors,
}

#[derive(Debug, Clone)]
pub struct UiTypography {
    pub font_size: UiFontSize,
    pub font_family: UiFontFamilies,
}

#[derive(Debug, Clone)]
pub struct UiLayout {
    pub spacing: f32,
    pub padding: UiSpacing,
    pub margin: UiSpacing,
    pub gap: UiSpacing,
    pub radius: UiRadius,
    pub border: UiSpacing,
}

#[derive(Debug, Clone)]
pub struct UiColors {
    pub white: UiColor,
    pub black: UiColor,
    pub gray: UiColor,
    pub mauve: UiColor,
    pub slate: UiColor,
    pub sage: UiColor,
    pub olive: UiColor,
    pub sand: UiColor,
    pub tomato: UiColor,
    pub red: UiColor,
    pub ruby: UiColor,
    pub crimson: UiColor,
    pub pink: UiColor,
    pub plum: UiColor,
    pub purple: UiColor,
    pub violet: UiColor,
    pub iris: UiColor,
    pub indigo: UiColor,
    pub blue: UiColor,
    pub cyan: UiColor,
    pub teal: UiColor,
    pub jade: UiColor,
    pub green: UiColor,
    pub grass: UiColor,
    pub bronze: UiColor,
    pub gold: UiColor,
    pub brown: UiColor,
    pub orange: UiColor,
    pub amber: UiColor,
    pub yellow: UiColor,
    pub lime: UiColor,
    pub mint: UiColor,
    pub sky: UiColor,
}

#[derive(Debug, Clone)]
pub struct UiFontSize {
    pub xs: f32,
    pub sm: f32,
    pub base: f32,
    pub lg: f32,
    pub xl: f32,
    pub x2l: f32,
    pub x3l: f32,
    pub x4l: f32,
    pub x5l: f32,
    pub x6l: f32,
    pub x7l: f32,
    pub x8l: f32,
    pub x9l: f32,
}

#[derive(Debug, Clone)]
pub struct UiFontFamilies {
    pub default: Handle<Font>,
    pub sans: FontVariants,
    pub serif: FontVariants,
    pub mono: FontVariants,
}

#[derive(Debug, Clone)]
pub struct FontVariants {
    pub light: Handle<Font>,
    pub light_italic: Handle<Font>,
    pub regular: Handle<Font>,
    pub regular_italic: Handle<Font>,
    pub medium: Handle<Font>,
    pub medium_italic: Handle<Font>,
    pub bold: Handle<Font>,
    pub bold_italic: Handle<Font>,
}

#[derive(Debug, Clone)]
pub struct UiSpacing {
    pub xs: f32,
    pub sm: f32,
    pub base: f32,
    pub lg: f32,
    pub xl: f32,
    pub x2l: f32,
    pub x3l: f32,
    pub x4l: f32,
    pub x5l: f32,
}
#[derive(Debug, Clone)]
pub struct UiRadius {
    pub xs: f32,
    pub sm: f32,
    pub base: f32,
    pub lg: f32,
    pub xl: f32,
    pub x2l: f32,
    pub x3l: f32,
    pub x4l: f32,
    pub full: f32,
}

#[derive(Debug, Clone)]
pub struct UiColor {
    pub background_primary: Color,
    pub background_secondary: Color,

    pub interaction_primary: Color,
    pub interaction_secondary: Color,
    pub interaction_tertiary: Color,

    pub border_primary: Color,
    pub border_secondary: Color,
    pub border_tertiary: Color,

    pub solid_primary: Color,
    pub solid_secondary: Color,

    pub text_primary: Color,
    pub text_secondary: Color,
}

impl UiTheme {
    /// Baut aus den rohen Theme-Daten und der Config das Runtime-Theme
    pub fn build_from_data(
        asset_server: &AssetServer,
        data: &UiThemeData,
        config: &UiConfig,
    ) -> Self {
        let ui_scaling = data.ui_scaling;
        let rem = config.rem.unwrap_or(data.rem);

        // Hilfsfunktionen
        let load_font = |path: &str| {
            if path.is_empty() {
                Handle::default()
            } else {
                asset_server.load(path)
            }
        };
        let conv_color = |c: [f32; 4]| Color::srgba(c[0], c[1], c[2], c[3]);

        // Font-Handles
        let font = UiTypography {
            font_size: UiFontSize {
                xs: data.font.font_size.xs * rem * ui_scaling,
                sm: data.font.font_size.sm * rem * ui_scaling,
                base: data.font.font_size.base * rem * ui_scaling,
                lg: data.font.font_size.lg * rem * ui_scaling,
                xl: data.font.font_size.xl * rem * ui_scaling,
                x2l: data.font.font_size.x2l * rem * ui_scaling,
                x3l: data.font.font_size.x3l * rem * ui_scaling,
                x4l: data.font.font_size.x4l * rem * ui_scaling,
                x5l: data.font.font_size.x5l * rem * ui_scaling,
                x6l: data.font.font_size.x6l * rem * ui_scaling,
                x7l: data.font.font_size.x7l * rem * ui_scaling,
                x8l: data.font.font_size.x8l * rem * ui_scaling,
                x9l: data.font.font_size.x9l * rem * ui_scaling,
            },
            font_family: UiFontFamilies {
                default: load_font(&data.font.font_family.default),
                sans: FontVariants {
                    light: load_font(&data.font.font_family.sans.light),
                    light_italic: load_font(&data.font.font_family.sans.light_italic),
                    regular: load_font(&data.font.font_family.sans.regular),
                    regular_italic: load_font(&data.font.font_family.sans.regular_italic),
                    medium: load_font(&data.font.font_family.sans.medium),
                    medium_italic: load_font(&data.font.font_family.sans.medium_italic),
                    bold: load_font(&data.font.font_family.sans.bold),
                    bold_italic: load_font(&data.font.font_family.sans.bold_italic),
                },
                serif: FontVariants {
                    light: load_font(&data.font.font_family.serif.light),
                    light_italic: load_font(&data.font.font_family.serif.light_italic),
                    regular: load_font(&data.font.font_family.serif.regular),
                    regular_italic: load_font(&data.font.font_family.serif.regular_italic),
                    medium: load_font(&data.font.font_family.serif.medium),
                    medium_italic: load_font(&data.font.font_family.serif.medium_italic),
                    bold: load_font(&data.font.font_family.serif.bold),
                    bold_italic: load_font(&data.font.font_family.serif.bold_italic),
                },
                mono: FontVariants {
                    light: load_font(&data.font.font_family.mono.light),
                    light_italic: load_font(&data.font.font_family.mono.light_italic),
                    regular: load_font(&data.font.font_family.mono.regular),
                    regular_italic: load_font(&data.font.font_family.mono.regular_italic),
                    medium: load_font(&data.font.font_family.mono.medium),
                    medium_italic: load_font(&data.font.font_family.mono.medium_italic),
                    bold: load_font(&data.font.font_family.mono.bold),
                    bold_italic: load_font(&data.font.font_family.mono.bold_italic),
                },
                // serif, mono analog
            },
        };

        // Layout
        let base_spacing = data.layout.spacing * rem * ui_scaling;
        let layout = UiLayout {
            spacing: base_spacing,
            padding: UiSpacing {
                xs: data.layout.padding.xs * base_spacing,
                sm: data.layout.padding.sm * base_spacing,
                base: data.layout.padding.base * base_spacing,
                lg: data.layout.padding.lg * base_spacing,
                xl: data.layout.padding.xl * base_spacing,
                x2l: data.layout.padding.x2l * base_spacing,
                x3l: data.layout.padding.x3l * base_spacing,
                x4l: data.layout.padding.x4l * base_spacing,
                x5l: data.layout.padding.x5l * base_spacing,
            },
            margin: UiSpacing {
                xs: data.layout.margin.xs * base_spacing,
                sm: data.layout.margin.sm * base_spacing,
                base: data.layout.margin.base * base_spacing,
                lg: data.layout.margin.lg * base_spacing,
                xl: data.layout.margin.xl * base_spacing,
                x2l: data.layout.margin.x2l * base_spacing,
                x3l: data.layout.margin.x3l * base_spacing,
                x4l: data.layout.margin.x4l * base_spacing,
                x5l: data.layout.margin.x5l * base_spacing,
            },
            gap: UiSpacing {
                xs: data.layout.gap.xs * base_spacing,
                sm: data.layout.gap.sm * base_spacing,
                base: data.layout.gap.base * base_spacing,
                lg: data.layout.gap.lg * base_spacing,
                xl: data.layout.gap.xl * base_spacing,
                x2l: data.layout.gap.x2l * base_spacing,
                x3l: data.layout.gap.x3l * base_spacing,
                x4l: data.layout.gap.x4l * base_spacing,
                x5l: data.layout.gap.x5l * base_spacing,
            },
            radius: UiRadius {
                xs: data.layout.radius.xs * base_spacing,
                sm: data.layout.radius.sm * base_spacing,
                base: data.layout.radius.base * base_spacing,
                lg: data.layout.radius.lg * base_spacing,
                xl: data.layout.radius.xl * base_spacing,
                x2l: data.layout.radius.x2l * base_spacing,
                x3l: data.layout.radius.x3l * base_spacing,
                x4l: data.layout.radius.x4l * base_spacing,
                full: data.layout.radius.full * base_spacing,
            },
            border: UiSpacing {
                xs: data.layout.border.xs,
                sm: data.layout.border.sm,
                base: data.layout.border.base,
                lg: data.layout.border.lg,
                xl: data.layout.border.xl,
                x2l: data.layout.border.x2l,
                x3l: data.layout.border.x3l,
                x4l: data.layout.border.x4l,
                x5l: data.layout.border.x5l,
            },
            // margin, gap, radius, border analog
        };

        // Colors
        let color = UiColors {
            white: UiColor {
                background_primary: conv_color(data.color.white.background_primary),
                background_secondary: conv_color(data.color.white.background_secondary),
                interaction_primary: conv_color(data.color.white.interaction_primary),
                interaction_secondary: conv_color(data.color.white.interaction_secondary),
                interaction_tertiary: conv_color(data.color.white.interaction_tertiary),
                border_primary: conv_color(data.color.white.border_primary),
                border_secondary: conv_color(data.color.white.border_secondary),
                border_tertiary: conv_color(data.color.white.border_tertiary),
                solid_primary: conv_color(data.color.white.solid_primary),
                solid_secondary: conv_color(data.color.white.solid_secondary),
                text_primary: conv_color(data.color.white.text_primary),
                text_secondary: conv_color(data.color.white.text_secondary),
            },
            black: UiColor {
                background_primary: conv_color(data.color.black.background_primary),
                background_secondary: conv_color(data.color.black.background_secondary),
                interaction_primary: conv_color(data.color.black.interaction_primary),
                interaction_secondary: conv_color(data.color.black.interaction_secondary),
                interaction_tertiary: conv_color(data.color.black.interaction_tertiary),
                border_primary: conv_color(data.color.black.border_primary),
                border_secondary: conv_color(data.color.black.border_secondary),
                border_tertiary: conv_color(data.color.black.border_tertiary),
                solid_primary: conv_color(data.color.black.solid_primary),
                solid_secondary: conv_color(data.color.black.solid_secondary),
                text_primary: conv_color(data.color.black.text_primary),
                text_secondary: conv_color(data.color.black.text_secondary),
            },
            gray: UiColor {
                background_primary: conv_color(data.color.gray.background_primary),
                background_secondary: conv_color(data.color.gray.background_secondary),
                interaction_primary: conv_color(data.color.gray.interaction_primary),
                interaction_secondary: conv_color(data.color.gray.interaction_secondary),
                interaction_tertiary: conv_color(data.color.gray.interaction_tertiary),
                border_primary: conv_color(data.color.gray.border_primary),
                border_secondary: conv_color(data.color.gray.border_secondary),
                border_tertiary: conv_color(data.color.gray.border_tertiary),
                solid_primary: conv_color(data.color.gray.solid_primary),
                solid_secondary: conv_color(data.color.gray.solid_secondary),
                text_primary: conv_color(data.color.gray.text_primary),
                text_secondary: conv_color(data.color.gray.text_secondary),
            },
            mauve: UiColor {
                background_primary: conv_color(data.color.mauve.background_primary),
                background_secondary: conv_color(data.color.mauve.background_secondary),
                interaction_primary: conv_color(data.color.mauve.interaction_primary),
                interaction_secondary: conv_color(data.color.mauve.interaction_secondary),
                interaction_tertiary: conv_color(data.color.mauve.interaction_tertiary),
                border_primary: conv_color(data.color.mauve.border_primary),
                border_secondary: conv_color(data.color.mauve.border_secondary),
                border_tertiary: conv_color(data.color.mauve.border_tertiary),
                solid_primary: conv_color(data.color.mauve.solid_primary),
                solid_secondary: conv_color(data.color.mauve.solid_secondary),
                text_primary: conv_color(data.color.mauve.text_primary),
                text_secondary: conv_color(data.color.mauve.text_secondary),
            },
            slate: UiColor {
                background_primary: conv_color(data.color.slate.background_primary),
                background_secondary: conv_color(data.color.slate.background_secondary),
                interaction_primary: conv_color(data.color.slate.interaction_primary),
                interaction_secondary: conv_color(data.color.slate.interaction_secondary),
                interaction_tertiary: conv_color(data.color.slate.interaction_tertiary),
                border_primary: conv_color(data.color.slate.border_primary),
                border_secondary: conv_color(data.color.slate.border_secondary),
                border_tertiary: conv_color(data.color.slate.border_tertiary),
                solid_primary: conv_color(data.color.slate.solid_primary),
                solid_secondary: conv_color(data.color.slate.solid_secondary),
                text_primary: conv_color(data.color.slate.text_primary),
                text_secondary: conv_color(data.color.slate.text_secondary),
            },
            sage: UiColor {
                background_primary: conv_color(data.color.sage.background_primary),
                background_secondary: conv_color(data.color.sage.background_secondary),
                interaction_primary: conv_color(data.color.sage.interaction_primary),
                interaction_secondary: conv_color(data.color.sage.interaction_secondary),
                interaction_tertiary: conv_color(data.color.sage.interaction_tertiary),
                border_primary: conv_color(data.color.sage.border_primary),
                border_secondary: conv_color(data.color.sage.border_secondary),
                border_tertiary: conv_color(data.color.sage.border_tertiary),
                solid_primary: conv_color(data.color.sage.solid_primary),
                solid_secondary: conv_color(data.color.sage.solid_secondary),
                text_primary: conv_color(data.color.sage.text_primary),
                text_secondary: conv_color(data.color.sage.text_secondary),
            },
            olive: UiColor {
                background_primary: conv_color(data.color.olive.background_primary),
                background_secondary: conv_color(data.color.olive.background_secondary),
                interaction_primary: conv_color(data.color.olive.interaction_primary),
                interaction_secondary: conv_color(data.color.olive.interaction_secondary),
                interaction_tertiary: conv_color(data.color.olive.interaction_tertiary),
                border_primary: conv_color(data.color.olive.border_primary),
                border_secondary: conv_color(data.color.olive.border_secondary),
                border_tertiary: conv_color(data.color.olive.border_tertiary),
                solid_primary: conv_color(data.color.olive.solid_primary),
                solid_secondary: conv_color(data.color.olive.solid_secondary),
                text_primary: conv_color(data.color.olive.text_primary),
                text_secondary: conv_color(data.color.olive.text_secondary),
            },
            sand: UiColor {
                background_primary: conv_color(data.color.sand.background_primary),
                background_secondary: conv_color(data.color.sand.background_secondary),
                interaction_primary: conv_color(data.color.sand.interaction_primary),
                interaction_secondary: conv_color(data.color.sand.interaction_secondary),
                interaction_tertiary: conv_color(data.color.sand.interaction_tertiary),
                border_primary: conv_color(data.color.sand.border_primary),
                border_secondary: conv_color(data.color.sand.border_secondary),
                border_tertiary: conv_color(data.color.sand.border_tertiary),
                solid_primary: conv_color(data.color.sand.solid_primary),
                solid_secondary: conv_color(data.color.sand.solid_secondary),
                text_primary: conv_color(data.color.sand.text_primary),
                text_secondary: conv_color(data.color.sand.text_secondary),
            },
            tomato: UiColor {
                background_primary: conv_color(data.color.tomato.background_primary),
                background_secondary: conv_color(data.color.tomato.background_secondary),
                interaction_primary: conv_color(data.color.tomato.interaction_primary),
                interaction_secondary: conv_color(data.color.tomato.interaction_secondary),
                interaction_tertiary: conv_color(data.color.tomato.interaction_tertiary),
                border_primary: conv_color(data.color.tomato.border_primary),
                border_secondary: conv_color(data.color.tomato.border_secondary),
                border_tertiary: conv_color(data.color.tomato.border_tertiary),
                solid_primary: conv_color(data.color.tomato.solid_primary),
                solid_secondary: conv_color(data.color.tomato.solid_secondary),
                text_primary: conv_color(data.color.tomato.text_primary),
                text_secondary: conv_color(data.color.tomato.text_secondary),
            },
            red: UiColor {
                background_primary: conv_color(data.color.red.background_primary),
                background_secondary: conv_color(data.color.red.background_secondary),
                interaction_primary: conv_color(data.color.red.interaction_primary),
                interaction_secondary: conv_color(data.color.red.interaction_secondary),
                interaction_tertiary: conv_color(data.color.red.interaction_tertiary),
                border_primary: conv_color(data.color.red.border_primary),
                border_secondary: conv_color(data.color.red.border_secondary),
                border_tertiary: conv_color(data.color.red.border_tertiary),
                solid_primary: conv_color(data.color.red.solid_primary),
                solid_secondary: conv_color(data.color.red.solid_secondary),
                text_primary: conv_color(data.color.red.text_primary),
                text_secondary: conv_color(data.color.red.text_secondary),
            },
            ruby: UiColor {
                background_primary: conv_color(data.color.ruby.background_primary),
                background_secondary: conv_color(data.color.ruby.background_secondary),
                interaction_primary: conv_color(data.color.ruby.interaction_primary),
                interaction_secondary: conv_color(data.color.ruby.interaction_secondary),
                interaction_tertiary: conv_color(data.color.ruby.interaction_tertiary),
                border_primary: conv_color(data.color.ruby.border_primary),
                border_secondary: conv_color(data.color.ruby.border_secondary),
                border_tertiary: conv_color(data.color.ruby.border_tertiary),
                solid_primary: conv_color(data.color.ruby.solid_primary),
                solid_secondary: conv_color(data.color.ruby.solid_secondary),
                text_primary: conv_color(data.color.ruby.text_primary),
                text_secondary: conv_color(data.color.ruby.text_secondary),
            },
            crimson: UiColor {
                background_primary: conv_color(data.color.crimson.background_primary),
                background_secondary: conv_color(data.color.crimson.background_secondary),
                interaction_primary: conv_color(data.color.crimson.interaction_primary),
                interaction_secondary: conv_color(data.color.crimson.interaction_secondary),
                interaction_tertiary: conv_color(data.color.crimson.interaction_tertiary),
                border_primary: conv_color(data.color.crimson.border_primary),
                border_secondary: conv_color(data.color.crimson.border_secondary),
                border_tertiary: conv_color(data.color.crimson.border_tertiary),
                solid_primary: conv_color(data.color.crimson.solid_primary),
                solid_secondary: conv_color(data.color.crimson.solid_secondary),
                text_primary: conv_color(data.color.crimson.text_primary),
                text_secondary: conv_color(data.color.crimson.text_secondary),
            },
            pink: UiColor {
                background_primary: conv_color(data.color.pink.background_primary),
                background_secondary: conv_color(data.color.pink.background_secondary),
                interaction_primary: conv_color(data.color.pink.interaction_primary),
                interaction_secondary: conv_color(data.color.pink.interaction_secondary),
                interaction_tertiary: conv_color(data.color.pink.interaction_tertiary),
                border_primary: conv_color(data.color.pink.border_primary),
                border_secondary: conv_color(data.color.pink.border_secondary),
                border_tertiary: conv_color(data.color.pink.border_tertiary),
                solid_primary: conv_color(data.color.pink.solid_primary),
                solid_secondary: conv_color(data.color.pink.solid_secondary),
                text_primary: conv_color(data.color.pink.text_primary),
                text_secondary: conv_color(data.color.pink.text_secondary),
            },
            plum: UiColor {
                background_primary: conv_color(data.color.plum.background_primary),
                background_secondary: conv_color(data.color.plum.background_secondary),
                interaction_primary: conv_color(data.color.plum.interaction_primary),
                interaction_secondary: conv_color(data.color.plum.interaction_secondary),
                interaction_tertiary: conv_color(data.color.plum.interaction_tertiary),
                border_primary: conv_color(data.color.plum.border_primary),
                border_secondary: conv_color(data.color.plum.border_secondary),
                border_tertiary: conv_color(data.color.plum.border_tertiary),
                solid_primary: conv_color(data.color.plum.solid_primary),
                solid_secondary: conv_color(data.color.plum.solid_secondary),
                text_primary: conv_color(data.color.plum.text_primary),
                text_secondary: conv_color(data.color.plum.text_secondary),
            },
            purple: UiColor {
                background_primary: conv_color(data.color.purple.background_primary),
                background_secondary: conv_color(data.color.purple.background_secondary),
                interaction_primary: conv_color(data.color.purple.interaction_primary),
                interaction_secondary: conv_color(data.color.purple.interaction_secondary),
                interaction_tertiary: conv_color(data.color.purple.interaction_tertiary),
                border_primary: conv_color(data.color.purple.border_primary),
                border_secondary: conv_color(data.color.purple.border_secondary),
                border_tertiary: conv_color(data.color.purple.border_tertiary),
                solid_primary: conv_color(data.color.purple.solid_primary),
                solid_secondary: conv_color(data.color.purple.solid_secondary),
                text_primary: conv_color(data.color.purple.text_primary),
                text_secondary: conv_color(data.color.purple.text_secondary),
            },
            violet: UiColor {
                background_primary: conv_color(data.color.violet.background_primary),
                background_secondary: conv_color(data.color.violet.background_secondary),
                interaction_primary: conv_color(data.color.violet.interaction_primary),
                interaction_secondary: conv_color(data.color.violet.interaction_secondary),
                interaction_tertiary: conv_color(data.color.violet.interaction_tertiary),
                border_primary: conv_color(data.color.violet.border_primary),
                border_secondary: conv_color(data.color.violet.border_secondary),
                border_tertiary: conv_color(data.color.violet.border_tertiary),
                solid_primary: conv_color(data.color.violet.solid_primary),
                solid_secondary: conv_color(data.color.violet.solid_secondary),
                text_primary: conv_color(data.color.violet.text_primary),
                text_secondary: conv_color(data.color.violet.text_secondary),
            },
            iris: UiColor {
                background_primary: conv_color(data.color.iris.background_primary),
                background_secondary: conv_color(data.color.iris.background_secondary),
                interaction_primary: conv_color(data.color.iris.interaction_primary),
                interaction_secondary: conv_color(data.color.iris.interaction_secondary),
                interaction_tertiary: conv_color(data.color.iris.interaction_tertiary),
                border_primary: conv_color(data.color.iris.border_primary),
                border_secondary: conv_color(data.color.iris.border_secondary),
                border_tertiary: conv_color(data.color.iris.border_tertiary),
                solid_primary: conv_color(data.color.iris.solid_primary),
                solid_secondary: conv_color(data.color.iris.solid_secondary),
                text_primary: conv_color(data.color.iris.text_primary),
                text_secondary: conv_color(data.color.iris.text_secondary),
            },
            indigo: UiColor {
                background_primary: conv_color(data.color.indigo.background_primary),
                background_secondary: conv_color(data.color.indigo.background_secondary),
                interaction_primary: conv_color(data.color.indigo.interaction_primary),
                interaction_secondary: conv_color(data.color.indigo.interaction_secondary),
                interaction_tertiary: conv_color(data.color.indigo.interaction_tertiary),
                border_primary: conv_color(data.color.indigo.border_primary),
                border_secondary: conv_color(data.color.indigo.border_secondary),
                border_tertiary: conv_color(data.color.indigo.border_tertiary),
                solid_primary: conv_color(data.color.indigo.solid_primary),
                solid_secondary: conv_color(data.color.indigo.solid_secondary),
                text_primary: conv_color(data.color.indigo.text_primary),
                text_secondary: conv_color(data.color.indigo.text_secondary),
            },
            blue: UiColor {
                background_primary: conv_color(data.color.blue.background_primary),
                background_secondary: conv_color(data.color.blue.background_secondary),
                interaction_primary: conv_color(data.color.blue.interaction_primary),
                interaction_secondary: conv_color(data.color.blue.interaction_secondary),
                interaction_tertiary: conv_color(data.color.blue.interaction_tertiary),
                border_primary: conv_color(data.color.blue.border_primary),
                border_secondary: conv_color(data.color.blue.border_secondary),
                border_tertiary: conv_color(data.color.blue.border_tertiary),
                solid_primary: conv_color(data.color.blue.solid_primary),
                solid_secondary: conv_color(data.color.blue.solid_secondary),
                text_primary: conv_color(data.color.blue.text_primary),
                text_secondary: conv_color(data.color.blue.text_secondary),
            },
            cyan: UiColor {
                background_primary: conv_color(data.color.cyan.background_primary),
                background_secondary: conv_color(data.color.cyan.background_secondary),
                interaction_primary: conv_color(data.color.cyan.interaction_primary),
                interaction_secondary: conv_color(data.color.cyan.interaction_secondary),
                interaction_tertiary: conv_color(data.color.cyan.interaction_tertiary),
                border_primary: conv_color(data.color.cyan.border_primary),
                border_secondary: conv_color(data.color.cyan.border_secondary),
                border_tertiary: conv_color(data.color.cyan.border_tertiary),
                solid_primary: conv_color(data.color.cyan.solid_primary),
                solid_secondary: conv_color(data.color.cyan.solid_secondary),
                text_primary: conv_color(data.color.cyan.text_primary),
                text_secondary: conv_color(data.color.cyan.text_secondary),
            },
            teal: UiColor {
                background_primary: conv_color(data.color.teal.background_primary),
                background_secondary: conv_color(data.color.teal.background_secondary),
                interaction_primary: conv_color(data.color.teal.interaction_primary),
                interaction_secondary: conv_color(data.color.teal.interaction_secondary),
                interaction_tertiary: conv_color(data.color.teal.interaction_tertiary),
                border_primary: conv_color(data.color.teal.border_primary),
                border_secondary: conv_color(data.color.teal.border_secondary),
                border_tertiary: conv_color(data.color.teal.border_tertiary),
                solid_primary: conv_color(data.color.teal.solid_primary),
                solid_secondary: conv_color(data.color.teal.solid_secondary),
                text_primary: conv_color(data.color.teal.text_primary),
                text_secondary: conv_color(data.color.teal.text_secondary),
            },
            jade: UiColor {
                background_primary: conv_color(data.color.jade.background_primary),
                background_secondary: conv_color(data.color.jade.background_secondary),
                interaction_primary: conv_color(data.color.jade.interaction_primary),
                interaction_secondary: conv_color(data.color.jade.interaction_secondary),
                interaction_tertiary: conv_color(data.color.jade.interaction_tertiary),
                border_primary: conv_color(data.color.jade.border_primary),
                border_secondary: conv_color(data.color.jade.border_secondary),
                border_tertiary: conv_color(data.color.jade.border_tertiary),
                solid_primary: conv_color(data.color.jade.solid_primary),
                solid_secondary: conv_color(data.color.jade.solid_secondary),
                text_primary: conv_color(data.color.jade.text_primary),
                text_secondary: conv_color(data.color.jade.text_secondary),
            },
            green: UiColor {
                background_primary: conv_color(data.color.green.background_primary),
                background_secondary: conv_color(data.color.green.background_secondary),
                interaction_primary: conv_color(data.color.green.interaction_primary),
                interaction_secondary: conv_color(data.color.green.interaction_secondary),
                interaction_tertiary: conv_color(data.color.green.interaction_tertiary),
                border_primary: conv_color(data.color.green.border_primary),
                border_secondary: conv_color(data.color.green.border_secondary),
                border_tertiary: conv_color(data.color.green.border_tertiary),
                solid_primary: conv_color(data.color.green.solid_primary),
                solid_secondary: conv_color(data.color.green.solid_secondary),
                text_primary: conv_color(data.color.green.text_primary),
                text_secondary: conv_color(data.color.green.text_secondary),
            },
            grass: UiColor {
                background_primary: conv_color(data.color.grass.background_primary),
                background_secondary: conv_color(data.color.grass.background_secondary),
                interaction_primary: conv_color(data.color.grass.interaction_primary),
                interaction_secondary: conv_color(data.color.grass.interaction_secondary),
                interaction_tertiary: conv_color(data.color.grass.interaction_tertiary),
                border_primary: conv_color(data.color.grass.border_primary),
                border_secondary: conv_color(data.color.grass.border_secondary),
                border_tertiary: conv_color(data.color.grass.border_tertiary),
                solid_primary: conv_color(data.color.grass.solid_primary),
                solid_secondary: conv_color(data.color.grass.solid_secondary),
                text_primary: conv_color(data.color.grass.text_primary),
                text_secondary: conv_color(data.color.grass.text_secondary),
            },
            bronze: UiColor {
                background_primary: conv_color(data.color.bronze.background_primary),
                background_secondary: conv_color(data.color.bronze.background_secondary),
                interaction_primary: conv_color(data.color.bronze.interaction_primary),
                interaction_secondary: conv_color(data.color.bronze.interaction_secondary),
                interaction_tertiary: conv_color(data.color.bronze.interaction_tertiary),
                border_primary: conv_color(data.color.bronze.border_primary),
                border_secondary: conv_color(data.color.bronze.border_secondary),
                border_tertiary: conv_color(data.color.bronze.border_tertiary),
                solid_primary: conv_color(data.color.bronze.solid_primary),
                solid_secondary: conv_color(data.color.bronze.solid_secondary),
                text_primary: conv_color(data.color.bronze.text_primary),
                text_secondary: conv_color(data.color.bronze.text_secondary),
            },
            gold: UiColor {
                background_primary: conv_color(data.color.gold.background_primary),
                background_secondary: conv_color(data.color.gold.background_secondary),
                interaction_primary: conv_color(data.color.gold.interaction_primary),
                interaction_secondary: conv_color(data.color.gold.interaction_secondary),
                interaction_tertiary: conv_color(data.color.gold.interaction_tertiary),
                border_primary: conv_color(data.color.gold.border_primary),
                border_secondary: conv_color(data.color.gold.border_secondary),
                border_tertiary: conv_color(data.color.gold.border_tertiary),
                solid_primary: conv_color(data.color.gold.solid_primary),
                solid_secondary: conv_color(data.color.gold.solid_secondary),
                text_primary: conv_color(data.color.gold.text_primary),
                text_secondary: conv_color(data.color.gold.text_secondary),
            },
            brown: UiColor {
                background_primary: conv_color(data.color.brown.background_primary),
                background_secondary: conv_color(data.color.brown.background_secondary),
                interaction_primary: conv_color(data.color.brown.interaction_primary),
                interaction_secondary: conv_color(data.color.brown.interaction_secondary),
                interaction_tertiary: conv_color(data.color.brown.interaction_tertiary),
                border_primary: conv_color(data.color.brown.border_primary),
                border_secondary: conv_color(data.color.brown.border_secondary),
                border_tertiary: conv_color(data.color.brown.border_tertiary),
                solid_primary: conv_color(data.color.brown.solid_primary),
                solid_secondary: conv_color(data.color.brown.solid_secondary),
                text_primary: conv_color(data.color.brown.text_primary),
                text_secondary: conv_color(data.color.brown.text_secondary),
            },
            orange: UiColor {
                background_primary: conv_color(data.color.orange.background_primary),
                background_secondary: conv_color(data.color.orange.background_secondary),
                interaction_primary: conv_color(data.color.orange.interaction_primary),
                interaction_secondary: conv_color(data.color.orange.interaction_secondary),
                interaction_tertiary: conv_color(data.color.orange.interaction_tertiary),
                border_primary: conv_color(data.color.orange.border_primary),
                border_secondary: conv_color(data.color.orange.border_secondary),
                border_tertiary: conv_color(data.color.orange.border_tertiary),
                solid_primary: conv_color(data.color.orange.solid_primary),
                solid_secondary: conv_color(data.color.orange.solid_secondary),
                text_primary: conv_color(data.color.orange.text_primary),
                text_secondary: conv_color(data.color.orange.text_secondary),
            },
            amber: UiColor {
                background_primary: conv_color(data.color.amber.background_primary),
                background_secondary: conv_color(data.color.amber.background_secondary),
                interaction_primary: conv_color(data.color.amber.interaction_primary),
                interaction_secondary: conv_color(data.color.amber.interaction_secondary),
                interaction_tertiary: conv_color(data.color.amber.interaction_tertiary),
                border_primary: conv_color(data.color.amber.border_primary),
                border_secondary: conv_color(data.color.amber.border_secondary),
                border_tertiary: conv_color(data.color.amber.border_tertiary),
                solid_primary: conv_color(data.color.amber.solid_primary),
                solid_secondary: conv_color(data.color.amber.solid_secondary),
                text_primary: conv_color(data.color.amber.text_primary),
                text_secondary: conv_color(data.color.amber.text_secondary),
            },
            yellow: UiColor {
                background_primary: conv_color(data.color.yellow.background_primary),
                background_secondary: conv_color(data.color.yellow.background_secondary),
                interaction_primary: conv_color(data.color.yellow.interaction_primary),
                interaction_secondary: conv_color(data.color.yellow.interaction_secondary),
                interaction_tertiary: conv_color(data.color.yellow.interaction_tertiary),
                border_primary: conv_color(data.color.yellow.border_primary),
                border_secondary: conv_color(data.color.yellow.border_secondary),
                border_tertiary: conv_color(data.color.yellow.border_tertiary),
                solid_primary: conv_color(data.color.yellow.solid_primary),
                solid_secondary: conv_color(data.color.yellow.solid_secondary),
                text_primary: conv_color(data.color.yellow.text_primary),
                text_secondary: conv_color(data.color.yellow.text_secondary),
            },
            lime: UiColor {
                background_primary: conv_color(data.color.lime.background_primary),
                background_secondary: conv_color(data.color.lime.background_secondary),
                interaction_primary: conv_color(data.color.lime.interaction_primary),
                interaction_secondary: conv_color(data.color.lime.interaction_secondary),
                interaction_tertiary: conv_color(data.color.lime.interaction_tertiary),
                border_primary: conv_color(data.color.lime.border_primary),
                border_secondary: conv_color(data.color.lime.border_secondary),
                border_tertiary: conv_color(data.color.lime.border_tertiary),
                solid_primary: conv_color(data.color.lime.solid_primary),
                solid_secondary: conv_color(data.color.lime.solid_secondary),
                text_primary: conv_color(data.color.lime.text_primary),
                text_secondary: conv_color(data.color.lime.text_secondary),
            },
            mint: UiColor {
                background_primary: conv_color(data.color.mint.background_primary),
                background_secondary: conv_color(data.color.mint.background_secondary),
                interaction_primary: conv_color(data.color.mint.interaction_primary),
                interaction_secondary: conv_color(data.color.mint.interaction_secondary),
                interaction_tertiary: conv_color(data.color.mint.interaction_tertiary),
                border_primary: conv_color(data.color.mint.border_primary),
                border_secondary: conv_color(data.color.mint.border_secondary),
                border_tertiary: conv_color(data.color.mint.border_tertiary),
                solid_primary: conv_color(data.color.mint.solid_primary),
                solid_secondary: conv_color(data.color.mint.solid_secondary),
                text_primary: conv_color(data.color.mint.text_primary),
                text_secondary: conv_color(data.color.mint.text_secondary),
            },
            sky: UiColor {
                background_primary: conv_color(data.color.sky.background_primary),
                background_secondary: conv_color(data.color.sky.background_secondary),
                interaction_primary: conv_color(data.color.sky.interaction_primary),
                interaction_secondary: conv_color(data.color.sky.interaction_secondary),
                interaction_tertiary: conv_color(data.color.sky.interaction_tertiary),
                border_primary: conv_color(data.color.sky.border_primary),
                border_secondary: conv_color(data.color.sky.border_secondary),
                border_tertiary: conv_color(data.color.sky.border_tertiary),
                solid_primary: conv_color(data.color.sky.solid_primary),
                solid_secondary: conv_color(data.color.sky.solid_secondary),
                text_primary: conv_color(data.color.sky.text_primary),
                text_secondary: conv_color(data.color.sky.text_secondary),
            },
            // black, gray, … sky analog
        };

        UiTheme {
            ui_scaling,
            rem,
            font,
            layout,
            color,
        }
    }
}
