use super::components::AlertDialogId;
use crate::components::dialog::CloseDialogEvent;
use bevy::prelude::*;

/// Emitted when the user confirms or cancels an alert dialog.
#[derive(Event, Debug, Clone)]
pub struct AlertDialogResultEvent {
    pub id: AlertDialogId,
    pub confirmed: bool,
}

/// Internal actions generated by the alert dialog buttons.
#[derive(Component, Debug, Clone, PartialEq, Eq)]
pub enum AlertDialogAction {
    Confirm(AlertDialogId),
    Cancel(AlertDialogId),
}

impl Default for AlertDialogAction {
    fn default() -> Self {
        // Use a unique id for a default action; adjust as needed.
        AlertDialogAction::Cancel(AlertDialogId::new_unique())
    }
}

impl AlertDialogResultEvent {
    pub fn confirmed(id: AlertDialogId) -> Self {
        Self {
            id,
            confirmed: true,
        }
    }
    pub fn cancelled(id: AlertDialogId) -> Self {
        Self {
            id,
            confirmed: false,
        }
    }
}

/// Helper to convert button clicks into result and close events.
pub fn handle_alert_dialog_actions(
    mut ev_button: EventReader<crate::components::button::ButtonClickedEvent<AlertDialogAction>>,
    mut ev_result: EventWriter<AlertDialogResultEvent>,
    mut ev_close: EventWriter<CloseDialogEvent>,
) {
    for event in ev_button.read() {
        if let Some(action) = &event.action_id {
            match action {
                AlertDialogAction::Confirm(id) => {
                    ev_result.write(AlertDialogResultEvent::confirmed(*id));
                    ev_close.write(CloseDialogEvent::specific((*id).into()));
                }
                AlertDialogAction::Cancel(id) => {
                    ev_result.write(AlertDialogResultEvent::cancelled(*id));
                    ev_close.write(CloseDialogEvent::specific((*id).into()));
                }
            }
        }
    }
}
